name: CI
on: [push, pull_request]
#  push:
#    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8, 3.9, 3.11]

    steps:
    - uses: actions/checkout@v3

    - name: Build using Python ${{ matrix.python-version }}
      uses: actions/checkout@v3
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies (pip)
      run: |
        python -m pip install pip --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        pip install -e .

#    - name: Run linter.py (with custom .pylintrc)
#      run: linter.py ./test/linter/
#      continue-on-error: false

    - name: Run unit tests
      run: python -m unittest discover "test_*.py"
